name: Gradle build and publish package to local

on:
  workflow_call:
    inputs:
      as-container-name:
        required: true
        type: string
    secrets:
      as-conn-string:
        required: true
      external-maven-repo-password:
        required: true

jobs:
  build:
    name: Gradle build and test.
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
          cache: 'gradle'
      - name: Set gradlew executable
        run: chmod +x gradlew
      - name: Set image version by tag
        run: echo "PACKAGE_VERSION=$GITHUB_REF_NAME" >> $GITHUB_ENV
        if: github.ref_type == 'tag'
      - name: Set image version by property
        run: echo "PACKAGE_VERSION=$(grep "^version=" gradle.properties | cut -d'=' -f2 | tr -d '[:space:]')" >> $GITHUB_ENV
        if: github.ref_type != 'tag'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build with Gradle
        run: ./gradlew build -Pversion=${{ env.PACKAGE_VERSION }}
        env:
          ORG_GRADLE_PROJECT_externalMavenRepoUrl: https://pkgs.dev.azure.com/ColdChainConn/_packaging/conn_api/maven/v1
          ORG_GRADLE_PROJECT_externalUsername: ColdChainConn
          ORG_GRADLE_PROJECT_externalPassword: ${{ secrets.external-maven-repo-password }}
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/libs/*.jar
      - name: Upload test report if build failed
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-reports
          path: '**/build/reports/**/*'
          retention-days: 5

  publish:
    runs-on: [ ubuntu-latest ]
    needs: build
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: "\\artifacts"
      - name: Azure Blob Storage Upload
        id: az-s-upload
        uses: copelandsoftware/azure-blob-storage-upload@main
        with:
          connection_string: ${{ secrets.as-conn-string }}
          container_name: ${{ inputs.as-container-name }}
          #sas_token: ${{ secrets.AZURE_STORAGE_SAS_TOKEN }}
          source_dir: "\\artifacts"
          extra_args: '--pattern *.jar --destination-path artifacts/${{ github.repository }}/${{ github.ref_name }}'
          overwrite: false
      - name: Delete artifacts
        uses: copelandsoftware/delete-artifact@v5
        with:
          name: build-artifacts




