name: Deploy to aks

on:
  workflow_call:
    inputs:
      deploy-to:
        required: true
        type: string
      cluster-name:
        required: true
        type: string
      resource-group:
        required: true
        type: string
      replicas:
        required: false
        type: string
        default: '1'
      manifest-file:
        required: false
        type: string
        default: 'k8s.yaml'
    secrets:
      azure-credentials:
        required: true
jobs:
  deploy:
    name: Deploy to ${{ inputs.deploy-to }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set image version by tag
      run: echo "IMAGE_VERSION=$GITHUB_REF_NAME" >> $GITHUB_ENV
      if: github.ref_type == 'tag'
    - name: Set image version by property
      run: echo "IMAGE_VERSION=$(grep "^version=" gradle.properties | cut -d'=' -f2 | tr -d '[:space:]')" >> $GITHUB_ENV
      if: github.ref_type != 'tag'
    - name: update replicas
      run: |
        sed -i "s/@replicas@/${{ inputs.replicas }}/g" ${{ inputs.manifest-file }}
        sed -i "s/@version@/$IMAGE_VERSION/g" ${{ inputs.manifest-file }}
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.azure-credentials }}
    # Set the target Azure Kubernetes Service (AKS) cluster.
    - uses: azure/aks-set-context@v3.2
      with:
        cluster-name: ${{ inputs.cluster-name }}
        resource-group: ${{ inputs.resource-group }}
      # Deploy app to AKS
    - uses: Azure/k8s-deploy@v4
      with:
        manifests: ${{ inputs.manifest-file }}
