name: Gradle build

on:
  workflow_call:
    secrets:
      external-maven-repo-password:
        required: true
jobs:
  build:
    name: Gradle build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        cache: 'gradle'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Set gradlew executable
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
      env:
        ORG_GRADLE_PROJECT_externalMavenRepoUrl: https://pkgs.dev.azure.com/ColdChainConn/_packaging/conn_api/maven/v1
        ORG_GRADLE_PROJECT_externalUsername: ColdChainConn
        ORG_GRADLE_PROJECT_externalPassword: ${{ secrets.external-maven-repo-password }}
