name: Gradle build test and sonar scan

on:
  workflow_call:
    secrets:
      external-maven-repo-password:
        required: true
jobs:
  build:
    name: Gradle build, test and publish
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        cache: 'gradle'
    - name: Debug
      run: |
       echo '${{ toJson(github) }}' > githubcontext.json
       cat githubcontext.json
    - name: Set package version by ref_name
      run: echo "PACKAGE_VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
    #- name: Set package version by tag
    #  run: echo "PACKAGE_VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
    #  if: github.ref_type == 'tag'
    #- name: Set package version by property
    #  run: echo "PACKAGE_VERSION=$(grep "^version=" gradle.properties | cut -d'=' -f2 | tr -d '[:space:]')" >> $GITHUB_ENV
    #  if: github.ref_type != 'tag'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Set gradlew executable
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build publish -Pversion=${{ env.PACKAGE_VERSION }}
      env:
        GITHUB_CI: "true"
        ORG_GRADLE_PROJECT_externalMavenRepoUrl: https://pkgs.dev.azure.com/ColdChainConn/_packaging/conn_api/maven/v1
        ORG_GRADLE_PROJECT_externalUsername: ColdChainConn
        ORG_GRADLE_PROJECT_externalPassword: ${{ secrets.external-maven-repo-password }}
