name: Gradle build test and sonar scan

on:
  workflow_call:
    secrets:
      external-maven-repo-password:
        required: true
      sonar-token:
        required: true
      githubToken:
        required: true
jobs:
  build:
    name: Gradle build, test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      pull-requests: read
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        cache: 'gradle'
    - name: Set gradlew executalbe
      run: chmod +x gradlew
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      env:
        SONAR_TOKEN: ${{ secrets.sonar-token }}
        SONAR_HOST_URL: https://sonarcloud.io
        GITHUB_TOKEN: ${{ secrets.githubToken }}
      with:
        arguments: build -PexternalPassword=${{ secrets.external-maven-repo-password }}
    - name: Upload test report if build failed
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: build-reports
        path: '**/build/reports/**/*'
        retention-days: 5
