name: Set environment variable

on:
  workflow_call:
    inputs:
      env-name:
        required: true
        type: string
      env-json:
        required: true
        type: string
    outputs:
      env-json:
        description: "Target environment to deploy"
        value: ${{ jobs.set-params.outputs.env-json }}
jobs:
  set-params:
    runs-on: ubuntu-latest
    outputs:
      env-json: ${{ steps.setValue.outputs.env-json }}
    steps:
      - id: setValue
        name: set values for ${{ inputs.env-name }}
        run: |
          echo '${{ toJson(fromJson(inputs.env-json)[inputs.env-name]) }}' > env.json
          if ${{ inputs.env-name =='staging'}}
          then
            echo "`jq '. + {"cred-prefix":"STAGING"}' env.json`" > env.json
          else
            echo "`jq '. + {"cred-prefix":"PROD"}' env.json`" > env.json
          fi
          envjson="`cat env.json`"
          envjson="${envjson//'%'/'%25'}"
          envjson="${envjson//$'\n'/'%0A'}"
          envjson="${envjson//$'\r'/'%0D'}"
          echo "env-json=$envjson" >> $GITHUB_OUTPUT